name: Run Tests and Publish Report

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests with PERSONAL API Key
        env:
          STAGING_PERSONAL_KEY: ${{ secrets.STAGING_PERSONAL_KEY }}
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
          PERSONAL_REPORT="report_${TIMESTAMP}_personal.html"
          pytest serverless_api/ \
            --html=${PERSONAL_REPORT} \
            --self-contained-html || true
          echo "PERSONAL_REPORT=${PERSONAL_REPORT}" >> $GITHUB_ENV

      - name: Run tests with TEAM API Key
        env:
          STAGING_TEAM_KEY: ${{ secrets.STAGING_TEAM_KEY }}
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
          TEAM_REPORT="report_${TIMESTAMP}_team.html"
          pytest serverless_api/ \
            --html=${TEAM_REPORT} \
            --self-contained-html || true
          echo "TEAM_REPORT=${TEAM_REPORT}" >> $GITHUB_ENV

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          persist-credentials: true 

      - name: Copy reports to gh-pages root
        run: |
          cp $PERSONAL_REPORT gh-pages/
          cp $TEAM_REPORT gh-pages/
          cp update_reports.py gh-pages/

      - name: Update index.html and cleanup old reports
        run: |
          cd gh-pages
          python3 update_reports.py

      - name: Commit and push reports
        run: |
          cd gh-pages
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add *.html
          git commit -m "Add test reports: $PERSONAL_REPORT and $TEAM_REPORT"
          git push origin gh-pages
